#!/usr/bin/env python3
"""check_asset_manifest.py -- the release-bundle checksum/manifest integrity gate.

DEFECT THIS EXISTS FOR (all four measured on /workspace/GSSC-S2D2-assets, 2026-08-20):

  D1  FOUR competing bookkeeping files ship in one bundle:
        ./MANIFEST.txt              54 lines, paths relative to the bundle root
        ./checksums.txt             62 entries, ditto
        ./checkpoints/MANIFEST.txt  37 lines, paths relative to checkpoints/
        ./checkpoints/checksums.txt 14 entries, ditto
      They DISAGREE. The two manifests give the JS3C+S2D2 row two different
      mIoUs (root: 26.1, checkpoints: 24.3) and only the inner one lists
      bev/bev_s2d2_scpnet/ at all. A downloader cannot tell which is
      authoritative, and each one is individually self-consistent, so no
      single-file check can see the contradiction.

  D2  `sha256sum -c checksums.txt` EXITS 1 today:
        checkpoints/MANIFEST.txt: FAILED
      recorded de582887..., on disk 9b7d57ba... -- the inner manifest was
      edited (Aug 16) after the outer checksum was taken (Jun 10). A checksum
      file that covers a file which keeps changing is a permanent red.

  D3  THREE files on disk are covered by NO checksum at all:
        checkpoints/bev/bev_s2d2_scpnet/config.json
        checkpoints/bev/bev_s2d2_scpnet/model.pt      (285 MB)
        checkpoints/checksums.txt
      Absence is invisible to `sha256sum -c`: it verifies what it lists and
      exits 0. Coverage has to be measured from the DISK side, which is the
      one direction the tool cannot check.

  D4  The inner checksums.txt covers 14 of the 65 files under checkpoints/ and
      exits 0. Running the wrong one of two authorities buys a green light over
      21% of the bundle. That is a disagreement about SCOPE, not about hashes,
      and hash-comparison alone reports it as consistent.

DESIGN NOTES
  * Coverage is measured disk -> checksums AND checksums -> disk. Both
    directions, because each is blind to a different failure.
  * A5 recomputes hashes in-process; A6 shells out to the real `sha256sum -c`
    the user would run. Two instruments on purpose: a reimplementation drifts
    from the tool (line format, binary-mode '*' prefix, escaped names), and the
    only way to notice is to run both.
  * Nothing is written under the assets. A6's selftest builds a symlink shadow
    in $TMPDIR so the real tree is hashed but the checksums file it verifies
    against is ours to corrupt.

STATUS WHEN WRITTEN (2026-08-20 ~03:00 UTC)
  All four defects above were repaired by the author BETWEEN the audit and this
  gate's first run: checkpoints/{MANIFEST,checksums}.txt were moved to
  _superseded_20260820/, the root pair was regenerated by make_manifest.py, and
  the three uncovered files gained entries. The gate therefore reads GREEN today.
  That is the point -- it exists to keep it green. Every check above was proved
  able to go red by --selftest, which synthesises the historical two-authority
  shape rather than skipping itself now that only one authority ships.
"""

from __future__ import annotations

import fnmatch
import hashlib
import json
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Dict, List, Set, Tuple

ASSETS = Path("/workspace/GSSC-S2D2-assets")
CKPT = ASSETS / "checkpoints"

# Scratch. /tmp deadlocks this box; never use it.
TMPDIR = Path(os.environ.get("TMPDIR") or "/workspace/.claude/jobs/d55ebe8b/tmp")

MANIFEST_RE = re.compile(r"^MANIFEST.*\.txt$", re.I)
CHECKSUM_RE = re.compile(r"^(checksums.*\.txt|.*\.sha256)$", re.I)

# A manifest row's key: a checkpoint subdir ('gssc_mf/gssc_31k_mf_step40000/') or a
# flat weight file. Anchored at line start so prose mentioning a path mid-sentence is
# not mistaken for a table row -- the inner manifest's trailing NOTE paragraphs quote
# both 26.1 and 24.3 and would otherwise be parsed as rows.
ROW_KEY_RE = re.compile(
    r"^(?:checkpoints/)?([A-Za-z0-9_]+/[A-Za-z0-9_.-]+/?|[A-Za-z0-9_.]+\.p(?:t|th))\s"
)
# The bundle declares its own release surface in the upload command in README.md:
#   huggingface-cli upload ... checkpoints/ --exclude "*.pt" --exclude "_superseded_*/*"
# Read that instead of hard-coding a belief about which files ship.
EXCLUDE_RE = re.compile(r'--exclude\s+"([^"]+)"')
# mIoU-shaped: two- or one-digit integer part with a decimal. Sizes ('264.9 MB',
# '265_MB') are excluded by requiring the number NOT be followed by a size unit.
MIOU_RE = re.compile(r"(?<![\d.])(\d{1,2}\.\d{1,2})(?!\s*(?:MB|GB|_MB|_GB|%))")


# --------------------------------------------------------------------------- world

class World:
    """All filesystem reads funnel through here so --selftest can perturb the INPUT
    rather than string-replacing a pattern that may have drifted (the classic way a
    selftest goes vacuous: a no-op .replace() against text that no longer matches)."""

    def __init__(self) -> None:
        self.text: Dict[str, str] = {}          # path -> overridden content
        self.extra: Dict[str, str] = {}         # virtual files (content by path)
        self.hidden: Set[str] = set()           # paths to pretend are absent
        self.hashes: Dict[str, str] = {}        # path -> overridden sha256
        self._cache: Dict[Tuple[str, int, int], str] = {}
        self._load_cache()

    # -- cache: hashing 12 GB takes ~9 s; keyed on (path, size, mtime_ns) so an
    # -- edited file is never served stale.
    @property
    def _cache_file(self) -> Path:
        return TMPDIR / "release_checks_sha256.json"

    def _load_cache(self) -> None:
        try:
            raw = json.loads(self._cache_file.read_text())
            self._cache = {tuple(json.loads(k)): v for k, v in raw.items()}  # type: ignore
        except Exception:
            self._cache = {}

    def _save_cache(self) -> None:
        try:
            TMPDIR.mkdir(parents=True, exist_ok=True)
            self._cache_file.write_text(json.dumps(
                {json.dumps(list(k)): v for k, v in self._cache.items()}))
        except OSError:
            pass

    def read_text(self, p: Path) -> str:
        k = str(p)
        if k in self.text:
            return self.text[k]
        if k in self.extra:
            return self.extra[k]
        return p.read_text(errors="replace")

    def exists(self, p: Path) -> bool:
        if str(p) in self.hidden:
            return False
        return p.is_file() or str(p) in self.extra

    def files_under(self, root: Path) -> List[Path]:
        """Regular files under root. followlinks=False: datasets/ is ALL symlinks into
        a 12 GB+ tree and walking it would take minutes and mean nothing."""
        out: List[Path] = []
        for dirpath, _dirs, names in os.walk(root, followlinks=False):
            for n in names:
                p = Path(dirpath) / n
                if p.is_file() and not p.is_symlink() and str(p) not in self.hidden:
                    out.append(p)
        for k in self.extra:
            q = Path(k)
            if str(q.parent).startswith(str(root)) and q not in out:
                out.append(q)
        return sorted(out)

    def sha256(self, p: Path) -> str:
        k = str(p)
        if k in self.hashes:
            return self.hashes[k]
        if k in self.extra:
            return hashlib.sha256(self.extra[k].encode()).hexdigest()
        st = p.stat()
        ck = (k, st.st_size, st.st_mtime_ns)
        if ck in self._cache:
            return self._cache[ck]
        h = hashlib.sha256()
        with open(p, "rb") as fh:
            for chunk in iter(lambda: fh.read(1 << 22), b""):
                h.update(chunk)
        self._cache[ck] = h.hexdigest()
        self._save_cache()
        return self._cache[ck]


# ----------------------------------------------------------------------- discovery

def bookkeeping_files(w: World) -> Tuple[List[Path], List[Path]]:
    mans, cks = [], []
    for p in w.files_under(ASSETS):
        if MANIFEST_RE.match(p.name):
            mans.append(p)
        elif CHECKSUM_RE.match(p.name):
            cks.append(p)
    return mans, cks


def parse_checksums(w: World, path: Path) -> Dict[Path, str]:
    """-> {absolute target: recorded hash}. Entries are relative to the file's OWN
    directory, which is exactly how sha256sum -c resolves them; getting this wrong
    would make the inner file look like it covered nothing."""
    out: Dict[Path, str] = {}
    for line in w.read_text(path).splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split(None, 1)
        if len(parts) != 2 or not re.fullmatch(r"[0-9a-f]{64}", parts[0]):
            continue
        target = parts[1].lstrip("*").strip()
        out[(path.parent / target).resolve()] = parts[0]
    return out


def manifest_dirs(w: World) -> Set[str]:
    """Checkpoint directories the bundle's own manifest enumerates, relative to
    checkpoints/. A file inside one of these is part of the release by the bundle's
    own account, so no exclusion pattern may exempt it from checksum coverage."""
    out: Set[str] = set()
    for m in bookkeeping_files(w)[0]:
        for key in parse_manifest_rows(w, m):
            if (CKPT / key).is_dir():
                out.add(key)
    return out


def release_surface(w: World) -> Tuple[List[Path], List[Path]]:
    """(files that must carry a checksum, files the bundle declares local-only)."""
    pats: List[str] = []
    readme = ASSETS / "README.md"
    if w.exists(readme):
        for line in w.read_text(readme).splitlines():
            if "checkpoints/" in line:
                pats += EXCLUDE_RE.findall(line)
    listed = manifest_dirs(w)
    must, local = [], []
    for p in w.files_under(CKPT):
        rel = p.relative_to(CKPT)
        inside_listed = any(str(rel).startswith(d + "/") for d in listed)
        # A '_'-prefixed path component is the bundle's quarantine convention
        # (pyramid/_superseded_20260820/). Kept separate from the declared patterns
        # so that losing the --exclude line cannot silently widen the exemption.
        quarantined = any(part.startswith("_") for part in rel.parts[:-1])
        excluded = quarantined or any(
            fnmatch.fnmatch(str(rel), pat) or fnmatch.fnmatch(rel.name, pat)
            for pat in pats)
        (local if (excluded and not inside_listed) else must).append(p)
    return must, local


def parse_manifest_rows(w: World, path: Path) -> Dict[str, Set[str]]:
    """-> {normalised checkpoint key: set of mIoU-shaped numbers on its row}."""
    rows: Dict[str, Set[str]] = {}
    for line in w.read_text(path).splitlines():
        m = ROW_KEY_RE.match(line.strip())
        if not m:
            continue
        key = m.group(1).rstrip("/")
        rows.setdefault(key, set()).update(MIOU_RE.findall(line))
    return rows


def authoritative_checksums(w: World, cks: List[Path]) -> Path:
    """The one with the widest coverage of checkpoints/ -- derived, not named, so
    renaming the file does not silently blind the gate."""
    disk = set(w.files_under(CKPT))
    return max(cks, key=lambda p: len(disk & set(parse_checksums(w, p))))


# -------------------------------------------------------------------------- checks

def a1_manifest_authority(w: World) -> List[str]:
    mans, _ = bookkeeping_files(w)
    if not mans:
        return [f"{ASSETS}: no MANIFEST*.txt found at all -- the gate has nothing to read"]
    if len(mans) == 1:
        return []
    bad: List[str] = []
    parsed = {p: parse_manifest_rows(w, p) for p in mans}
    base, *rest = mans
    for other in rest:
        a, b = parsed[base], parsed[other]
        for key in sorted(set(a) | set(b)):
            if key not in a:
                bad.append(f"{other}: lists '{key}' which {base.name} at "
                           f"{base} does not -- two manifests, two inventories")
            elif key not in b:
                bad.append(f"{base}: lists '{key}' which {other} does not")
            elif a[key] and b[key] and not (a[key] & b[key]):
                # DISJOINT, not merely unequal. One manifest legitimately carries extra
                # context numbers on the same row (a rounded value, a delta); demanding
                # set equality would manufacture a disagreement out of that.
                bad.append(f"'{key}': {base} says mIoU {sorted(a[key])} but "
                           f"{other} says {sorted(b[key])} -- no value in common")
    if not bad:
        bad.append(f"{len(mans)} manifests ship ({', '.join(str(p) for p in mans)}) and "
                   f"they happen to agree, but nothing marks which is authoritative")
    return bad


def a2_checksums_authority(w: World) -> List[str]:
    _, cks = bookkeeping_files(w)
    if not cks:
        return [f"{ASSETS}: no checksums file found at all"]
    if len(cks) == 1:
        return []
    bad: List[str] = []
    parsed = {p: parse_checksums(w, p) for p in cks}
    for i, p in enumerate(cks):
        for q in cks[i + 1:]:
            for tgt in sorted(set(parsed[p]) & set(parsed[q])):
                if parsed[p][tgt] != parsed[q][tgt]:
                    bad.append(f"{tgt}: {p} records {parsed[p][tgt][:12]}..., "
                               f"{q} records {parsed[q][tgt][:12]}...")
    # SCOPE disagreement. Hash-equality alone calls a 14-of-65 subset 'consistent';
    # but running that file exits 0 while 51 files go unverified, so a partial
    # authority sitting next to a fuller one is itself the defect.
    auth = authoritative_checksums(w, cks)
    for p in cks:
        if p.resolve() == auth.resolve():
            continue        # the widest-coverage file is the intended authority; a3
                            # measures ITS coverage. Only the RIVALS are the defect here.
        subtree = set(w.files_under(p.parent)) - {p.resolve()}
        covered = set(parsed[p])
        missed = subtree - covered
        if missed and len(covered) < len(subtree):
            bad.append(f"{p}: covers {len(covered & subtree)}/{len(subtree)} files under "
                       f"{p.parent} yet verifies clean -- a second, narrower authority "
                       f"(first uncovered: {sorted(missed)[0]})")
    return bad


def a3_disk_covered(w: World) -> List[str]:
    _, cks = bookkeeping_files(w)
    if not cks:
        return [f"{ASSETS}: no checksums file; every file under {CKPT} is unverified"]
    auth = authoritative_checksums(w, cks)
    recorded = set(parse_checksums(w, auth))
    must, local = release_surface(w)
    disk = [p for p in must if p.resolve() != auth.resolve()]
    if not disk:
        # BLIND-GUARD: an --exclude pattern wide enough to exempt the whole bundle
        # would let this check pass by measuring nothing.
        return [f"{ASSETS}/README.md: the declared --exclude patterns exempt every "
                f"file under {CKPT}; checksum coverage is unmeasurable"]
    missing = [p for p in disk if p.resolve() not in recorded]
    if not missing:
        return []
    # One line PER uncovered file: an aggregate line whose offender list is truncated
    # cannot be matched by name, and a gate whose detail cannot be matched cannot be
    # selftested. The count goes first so the progress signal is still one glance.
    out = [f"{auth}: {len(missing)}/{len(disk)} release files under {CKPT} carry no "
           f"checksum entry ({len(local)} more are declared local-only and exempt)"]
    out += [f"{auth}: no checksum entry for {p.relative_to(ASSETS)}" for p in missing]
    return out


def a4_entries_exist(w: World) -> List[str]:
    _, cks = bookkeeping_files(w)
    bad: List[str] = []
    for p in cks:
        for tgt in sorted(parse_checksums(w, p)):
            if not w.exists(tgt):
                bad.append(f"{p}: entry '{tgt}' does not exist on disk")
    return bad[:8]


def a5_hashes_match(w: World) -> List[str]:
    _, cks = bookkeeping_files(w)
    bad: List[str] = []
    for p in cks:
        for tgt, rec in sorted(parse_checksums(w, p).items()):
            if not w.exists(tgt):
                continue                      # a4 owns that failure
            got = w.sha256(tgt)
            if got != rec:
                bad.append(f"{p}: '{tgt}' recorded {rec[:12]}... but computes "
                           f"{got[:12]}... -- the recorded hash is stale")
    return bad


def _run_sha256sum(directory: Path, name: str) -> Tuple[int, str]:
    r = subprocess.run(["sha256sum", "-c", "--quiet", name], cwd=str(directory),
                       capture_output=True, text=True)
    return r.returncode, (r.stdout + r.stderr).strip()


def a6_verification_exits_zero(w: World) -> List[str]:
    """The reproducer's actual command. Kept separate from a5 because our parser and
    GNU coreutils can disagree (binary '*' prefix, backslash-escaped names, BOM) and
    a gate that only trusts its own parser cannot see that."""
    _, cks = bookkeeping_files(w)
    bad: List[str] = []
    for p in cks:
        d, name = p.parent, p.name
        if str(p) in w.text or str(p) in w.extra:   # selftest: verify a perturbed copy
            shadow = Path(tempfile.mkdtemp(prefix="ckshadow_", dir=TMPDIR))
            (shadow / name).write_text(w.read_text(p))
            for child in d.iterdir():         # symlinks: hash the REAL bytes, no copy
                if child.name != name:
                    (shadow / child.name).symlink_to(child)
            d, name = shadow, name
        rc, out = _run_sha256sum(d, name)
        if rc == 0:
            continue
        # Emit one line PER failing entry. Reporting only out.splitlines()[0] made the
        # gate unable to distinguish a new fault from the pre-existing stale entry --
        # and made its own selftest vacuous, which is how the bug was found.
        entries = [l for l in out.splitlines() if l.endswith(": FAILED")]
        for e in entries[:8]:
            bad.append(f"`cd {d} && sha256sum -c {name}` exits {rc}: {e}")
        if not entries:
            bad.append(f"`cd {d} && sha256sum -c {name}` exits {rc}: "
                       f"{out.splitlines()[0] if out else '(no output)'}")
    return bad


CHECKS = [
    ("manifest-single-authority", a1_manifest_authority),
    ("checksums-single-authority", a2_checksums_authority),
    ("every-release-file-has-a-checksum", a3_disk_covered),
    ("every-checksum-entry-exists", a4_entries_exist),
    ("recorded-hash-matches-disk", a5_hashes_match),
    ("sha256sum--c-exits-zero", a6_verification_exits_zero),
]


# ------------------------------------------------------------------------ selftest

def _mutate_manifest_authority(w: World) -> str:
    """Pick a row that BOTH manifests score and that currently agrees, then break the
    agreement. Mutating a row only one manifest scores (e.g. bev_direct_l3_deeper,
    which the inner manifest leaves numberless) changes the bytes and nothing else --
    a mutation that perturbs the file but not the MEASUREMENT."""
    mans, _ = bookkeeping_files(w)
    if len(mans) == 1:
        # The bundle used to ship two; it now ships one. Inject the historical shape
        # rather than declaring the fault un-injectable -- a selftest that skips
        # itself once the defect is fixed stops guarding the regression.
        rival = ASSETS / "MANIFEST_selftest_rival.txt"
        w.extra[str(rival)] = w.read_text(mans[0])
        mans = bookkeeping_files(w)[0]
        assert len(mans) == 2, "rival manifest was not picked up by discovery"
    parsed = {q: parse_manifest_rows(w, q) for q in mans}
    a, b = mans[0], mans[1]
    cand = [k for k in parsed[a] if k in parsed[b]
            and parsed[a][k] and parsed[b][k] and (parsed[a][k] & parsed[b][k])]
    assert cand, "no row is scored by both manifests and agrees -- nothing to break"
    key = sorted(cand)[0]
    # Edit whichever side has exactly one number, so the sets end up disjoint.
    tgt = a if len(parsed[a][key]) == 1 else b
    if str(tgt) not in w.extra and any(str(q) in w.extra for q in (a, b)):
        tgt = next(q for q in (a, b) if str(q) in w.extra)   # never edit a real file
    lines = w.read_text(tgt).splitlines()
    for i, line in enumerate(lines):
        m = ROW_KEY_RE.match(line.strip())
        if m and m.group(1).rstrip("/") == key:
            for num in MIOU_RE.findall(line):
                line = line.replace(num, "99.99")
            lines[i] = line
            break
    else:
        raise AssertionError(f"could not locate row {key} in {tgt}")
    before = w.read_text(tgt)
    w.text[str(tgt)] = "\n".join(lines)
    assert w.text[str(tgt)] != before, "mutation was a no-op"
    after = parse_manifest_rows(w, tgt)
    assert not (after[key] & parsed[b if tgt is a else a][key]), \
        "mutation left the two rows still overlapping"
    return key


def _mutate_checksums_disagree(w: World) -> str:
    _, cks = bookkeeping_files(w)
    if len(cks) == 1:
        # Rival authority in a SUBDIRECTORY: its entries are relative to its own dir,
        # which is the resolution rule the old checkpoints/checksums.txt exercised.
        auth = cks[0]
        entries = parse_checksums(w, auth)
        tgt = sorted(p for p in entries if str(p).startswith(str(CKPT)))[0]
        rival = CKPT / "checksums_selftest_rival.txt"
        w.extra[str(rival)] = f"{'0' * 64}  {tgt.relative_to(CKPT)}\n"
        cks = bookkeeping_files(w)[1]
        assert len(cks) == 2, "rival checksums file was not picked up by discovery"
        assert tgt in parse_checksums(w, rival), "rival entry did not resolve"
        return str(tgt)
    a, b = cks[0], cks[1]
    shared = sorted(set(parse_checksums(w, a)) & set(parse_checksums(w, b)))
    assert shared, "selftest needs an entry present in both checksums files"
    tgt = shared[0]
    txt = w.read_text(a)
    prev = parse_checksums(w, a)[tgt]
    upd = txt.replace(prev, "0" * 64, 1)
    assert upd != txt, "mutation was a no-op"
    w.text[str(a)] = upd
    return str(tgt)


def _mutate_hide_from_checksums(w: World) -> str:
    _, cks = bookkeeping_files(w)
    auth = authoritative_checksums(w, cks)
    entries = parse_checksums(w, auth)
    # pick a covered file and delete its line: coverage must notice
    tgt = sorted(entries)[0]
    txt = w.read_text(auth)
    new = "\n".join(l for l in txt.splitlines() if entries[tgt] not in l)
    assert new != txt, "mutation was a no-op"
    w.text[str(auth)] = new
    return str(tgt.relative_to(ASSETS))


def _mutate_dangling_entry(w: World) -> str:
    _, cks = bookkeeping_files(w)
    auth = authoritative_checksums(w, cks)
    tgt = sorted(parse_checksums(w, auth))[0]
    before = w.exists(tgt)
    w.hidden.add(str(tgt))
    assert before and not w.exists(tgt), "mutation was a no-op"
    return str(tgt)


def _mutate_bad_hash(w: World) -> str:
    _, cks = bookkeeping_files(w)
    auth = authoritative_checksums(w, cks)
    tgt = sorted(parse_checksums(w, auth))[0]
    real = w.sha256(tgt)
    w.hashes[str(tgt)] = "f" * 64
    assert w.sha256(tgt) != real, "mutation was a no-op"
    return str(tgt)


def _mutate_sha256sum_line(w: World) -> str:
    _, cks = bookkeeping_files(w)
    auth = authoritative_checksums(w, cks)
    entries = parse_checksums(w, auth)
    # smallest covered file: the shadow run still hashes the real bytes of everything
    # else, so pick a target whose corrupted line is unambiguous in the output.
    tgt = min((p for p in entries if p.is_file()), key=lambda p: p.stat().st_size)
    txt = w.read_text(auth)
    new = txt.replace(entries[tgt], "0" * 64, 1)
    assert new != txt, "mutation was a no-op"
    w.text[str(auth)] = new
    # The needle must be the name sha256sum ECHOES, not the absolute path.
    return str(tgt.relative_to(auth.parent))


MUTATIONS = {
    "manifest-single-authority": _mutate_manifest_authority,
    "checksums-single-authority": _mutate_checksums_disagree,
    "every-release-file-has-a-checksum": _mutate_hide_from_checksums,
    "every-checksum-entry-exists": _mutate_dangling_entry,
    "recorded-hash-matches-disk": _mutate_bad_hash,
    "sha256sum--c-exits-zero": _mutate_sha256sum_line,
}


def selftest() -> int:
    """A check that is ALREADY red cannot prove anything by staying red. So the bar is:
    the fault must produce a failure line naming the injected target that the clean
    baseline does not have."""
    missed: List[str] = []
    for name, fn in CHECKS:
        base = set(fn(World()))
        w = World()
        try:
            target = MUTATIONS[name](w)
        except AssertionError as e:
            print(f"  MISSED   {name}   (fault not injectable: {e})")
            missed.append(name)
            continue
        after = set(fn(w))
        new = [d for d in after - base if target in d]
        if new:
            print(f"  TRIPPED  {name}")
        else:
            print(f"  MISSED   {name}   (fault on {target} produced no new failure)")
            missed.append(name)
    n = len(CHECKS)
    if missed:
        print(f"SELFTEST FAILED: {n - len(missed)}/{n} checks provably fail when broken; "
              f"missed: {', '.join(missed)}")
        return 1
    print(f"SELFTEST OK: {n}/{n} checks provably fail when broken")
    return 0


def main() -> int:
    if "--selftest" in sys.argv:
        return selftest()
    w = World()
    failing = 0
    for name, fn in CHECKS:
        bad = fn(w)
        if bad:
            failing += 1
            print(f"  FAIL  {name}   ({bad[0]})")
            for extra in bad[1:6]:
                print(f"        + {extra}")
            if len(bad) > 6:
                print(f"        + ... {len(bad) - 6} more")
        else:
            print(f"  PASS  {name}")
    print(f"{'OK' if not failing else 'FAILED'}: {failing} failing check(s)")
    return 1 if failing else 0


if __name__ == "__main__":
    sys.exit(main())
